theme: jekyll-theme-minimal
title: The Portfolio of Renad AlKhaldi
description: Hello, World! The first words many of us write when learning to code. It feels like the perfect way to welcome you to my professional journey. Take a look around and explore my projects, experiences, and the path that brought me here.
header_pages:
  - about.md
